all:
	gcc -Wall -Wextra -Werror -pedantic -Og -ggdb3 -std=c99 main.c -o main -fopenmp

fast:
	gcc -Wall -Wextra -Werror -pedantic -Ofast -std=c99 main.c -o main -fopenmp

clean:
	rm main *.plot *.pdf
